name: Deploy Hexo to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    # Step 2: Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22  # Ensure this matches the version required by Hexo

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Generate the Hexo site
    - name: Generate site
      run: npm run build

    # Step 5: Deploy to FTP
    - name: Deploy
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USER: ${{ secrets.FTP_USER }}
        FTP_PASS: ${{ secrets.FTP_PASS }}
      run: npm run deploy
